import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800", "900"] });

export const metadata = {
    title: "Ryan Adi Putra",
    description:
        "Pulsify is an open source website traffic analytics tool, it helps users track and analyze their website traffic to understand visitor behavior and improve site performance.Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body
                className={`${poppins.className} bg-neutral-200 dark:bg-neutral-800 text-neutral-900 dark:text-neutral-50`}
            >
                {children}
            </body>
        </html>
    );
}
